services:
  scraper:
    build: .
    volumes:
      - .:/usr/src/app  # Ensure the entire project directory is mounted
      - ./images:/usr/src/app/images  # Directory for saving images
    working_dir: /usr/src/app  # Set the working directory to where `scrapy.cfg` resides
    depends_on:
      - db
    networks:
      - ecommerce_network
    command: scrapy crawl products  # Run the Scrapy spider on container start

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: Marjia
      POSTGRES_PASSWORD: Marjia029
      POSTGRES_DB: ecommerce
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"  # Port mapping for pgAdmin
    networks:
      - ecommerce_network

volumes:
  postgres_data:

networks:
  ecommerce_network:
